name: Display Author Name on Push

on:
  push:
    branches:
      - main

jobs:
  display-author:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show Author Name
        run: |
          echo "The author's name is ${{ secrets.AUTHOR_NAME }}"
